# Override para desarrollo local
# Este archivo se aplica automáticamente en desarrollo
# Para producción, usar: docker-compose -f docker-compose.yml up

services:
  backend:
    # Montar código para desarrollo con hot reload
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    # Para desarrollo, usar servidor de desarrollo de React
    build:
      target: builder
    command: ["npm", "start"]
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Desactivar nginx proxy en desarrollo
  nginx:
    profiles:
      - disabled