"""add comprobante field to asientos_contables

Revision ID: 60790d488b7a
Revises: 3cd11107c5bf
Create Date: 2025-08-06 16:24:18.982534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60790d488b7a'
down_revision: Union[str, Sequence[str], None] = '3cd11107c5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asientos_contables', sa.Column('comprobante', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_asientos_contables_comprobante'), 'asientos_contables', ['comprobante'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asientos_contables_comprobante'), table_name='asientos_contables')
    op.drop_column('asientos_contables', 'comprobante')
    # ### end Alembic commands ###
