"""add local_id and transferencia_id to movimientos_inventario

Revision ID: 83c1c173c069
Revises: 86bbc5bc734c
Create Date: 2025-08-20 20:51:50.816632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c1c173c069'
down_revision: Union[str, Sequence[str], None] = '86bbc5bc734c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asientos_contables', sa.Column('tienda_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_asientos_contables_tienda_id'), 'asientos_contables', ['tienda_id'], unique=False)
    op.create_foreign_key(None, 'asientos_contables', 'tiendas', ['tienda_id'], ['id'])
    op.add_column('clientes', sa.Column('tienda_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_clientes_tienda_id'), 'clientes', ['tienda_id'], unique=False)
    op.create_foreign_key(None, 'clientes', 'tiendas', ['tienda_id'], ['id'])
    op.add_column('cuentas_contables', sa.Column('tienda_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_cuentas_contables_tienda_id'), 'cuentas_contables', ['tienda_id'], unique=False)
    op.create_foreign_key(None, 'cuentas_contables', 'tiendas', ['tienda_id'], ['id'])
    op.add_column('facturas', sa.Column('tienda_id', sa.Uuid(), nullable=True))
    op.add_column('facturas', sa.Column('local_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_facturas_local_id'), 'facturas', ['local_id'], unique=False)
    op.create_index(op.f('ix_facturas_tienda_id'), 'facturas', ['tienda_id'], unique=False)
    op.create_foreign_key(None, 'facturas', 'tiendas', ['tienda_id'], ['id'])
    op.create_foreign_key(None, 'facturas', 'locales', ['local_id'], ['id'])
    op.add_column('movimientos_inventario', sa.Column('local_id', sa.Uuid(), nullable=True))
    op.add_column('movimientos_inventario', sa.Column('transferencia_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_movimientos_inventario_local_id'), 'movimientos_inventario', ['local_id'], unique=False)
    op.create_foreign_key(None, 'movimientos_inventario', 'locales', ['local_id'], ['id'])
    op.create_foreign_key(None, 'movimientos_inventario', 'transferencias_inventario', ['transferencia_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimientos_inventario', type_='foreignkey')
    op.drop_constraint(None, 'movimientos_inventario', type_='foreignkey')
    op.drop_index(op.f('ix_movimientos_inventario_local_id'), table_name='movimientos_inventario')
    op.drop_column('movimientos_inventario', 'transferencia_id')
    op.drop_column('movimientos_inventario', 'local_id')
    op.drop_constraint(None, 'facturas', type_='foreignkey')
    op.drop_constraint(None, 'facturas', type_='foreignkey')
    op.drop_index(op.f('ix_facturas_tienda_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_local_id'), table_name='facturas')
    op.drop_column('facturas', 'local_id')
    op.drop_column('facturas', 'tienda_id')
    op.drop_constraint(None, 'cuentas_contables', type_='foreignkey')
    op.drop_index(op.f('ix_cuentas_contables_tienda_id'), table_name='cuentas_contables')
    op.drop_column('cuentas_contables', 'tienda_id')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_index(op.f('ix_clientes_tienda_id'), table_name='clientes')
    op.drop_column('clientes', 'tienda_id')
    op.drop_constraint(None, 'asientos_contables', type_='foreignkey')
    op.drop_index(op.f('ix_asientos_contables_tienda_id'), table_name='asientos_contables')
    op.drop_column('asientos_contables', 'tienda_id')
    # ### end Alembic commands ###
