"""add multi-tenant support - tiendas, locales, stock_local, transferencias, usuario_locales

Revision ID: 86bbc5bc734c
Revises: 08b45c8844c3
Create Date: 2025-08-20 00:29:26.682845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '86bbc5bc734c'
down_revision: Union[str, Sequence[str], None] = '08b45c8844c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, create the new tables
    op.create_table('tiendas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dominio', sa.String(length=100), nullable=True),
    sa.Column('configuracion', sa.JSON(), nullable=True),
    sa.Column('consecutivo_facturas', sa.Integer(), nullable=False),
    sa.Column('prefijo_facturas', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dominio')
    )
    op.create_index(op.f('ix_tiendas_codigo'), 'tiendas', ['codigo'], unique=True)
    
    op.create_table('locales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tienda_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('departamento', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('codigo_postal', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('configuracion', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locales_codigo'), 'locales', ['codigo'], unique=False)
    op.create_index(op.f('ix_locales_tienda_id'), 'locales', ['tienda_id'], unique=False)
    
    # Insert default tienda and local for migration
    tienda_id = 'aaaaaaaa-bbbb-cccc-dddd-000000000001'
    local_id = 'aaaaaaaa-bbbb-cccc-dddd-000000000002'
    
    op.execute(f"""
        INSERT INTO tiendas (id, codigo, nombre, descripcion, consecutivo_facturas, prefijo_facturas, is_active, created_at)
        VALUES ('{tienda_id}', 'MAIN', 'Tienda Principal', 'Tienda por defecto para migración', 1, 'F', true, NOW())
    """)
    
    op.execute(f"""
        INSERT INTO locales (id, tienda_id, codigo, nombre, direccion, is_active, created_at)
        VALUES ('{local_id}', '{tienda_id}', 'LOCAL01', 'Local Principal', 'Dirección por defecto', true, NOW())
    """)
    
    op.create_table('stock_por_local',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('local_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('stock_maximo', sa.Integer(), nullable=True),
    sa.Column('costo_promedio', sa.DECIMAL(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('valor_total_inventario', sa.DECIMAL(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_por_local_local_id'), 'stock_por_local', ['local_id'], unique=False)
    op.create_index(op.f('ix_stock_por_local_producto_id'), 'stock_por_local', ['producto_id'], unique=False)
    
    op.create_table('transferencias_inventario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero_transferencia', sa.String(length=50), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('local_origen_id', sa.Uuid(), nullable=False),
    sa.Column('local_destino_id', sa.Uuid(), nullable=False),
    sa.Column('cantidad_solicitada', sa.Integer(), nullable=False),
    sa.Column('cantidad_enviada', sa.Integer(), nullable=False),
    sa.Column('cantidad_recibida', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ENVIADO', 'RECIBIDO', 'CANCELADO', name='estadotransferencia'), nullable=False),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('usuario_solicita_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_envia_id', sa.Uuid(), nullable=True),
    sa.Column('usuario_recibe_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['local_destino_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['local_origen_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['usuario_envia_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['usuario_recibe_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['usuario_solicita_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_transferencia')
    )
    op.create_index(op.f('ix_transferencias_inventario_local_destino_id'), 'transferencias_inventario', ['local_destino_id'], unique=False)
    op.create_index(op.f('ix_transferencias_inventario_local_origen_id'), 'transferencias_inventario', ['local_origen_id'], unique=False)
    op.create_index(op.f('ix_transferencias_inventario_producto_id'), 'transferencias_inventario', ['producto_id'], unique=False)
    
    op.create_table('usuario_locales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('local_id', sa.Uuid(), nullable=False),
    sa.Column('puede_vender', sa.Boolean(), nullable=False),
    sa.Column('puede_ver_stock', sa.Boolean(), nullable=False),
    sa.Column('puede_transferir', sa.Boolean(), nullable=False),
    sa.Column('es_responsable', sa.Boolean(), nullable=False),
    sa.Column('puede_modificar_precios', sa.Boolean(), nullable=False),
    sa.Column('puede_aplicar_descuentos', sa.Boolean(), nullable=False),
    sa.Column('puede_ver_reportes', sa.Boolean(), nullable=False),
    sa.Column('puede_gestionar_usuarios', sa.Boolean(), nullable=False),
    sa.Column('limite_descuento_porcentaje', sa.Float(), nullable=True),
    sa.Column('limite_credito_monto', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_locales_local_id'), 'usuario_locales', ['local_id'], unique=False)
    op.create_index(op.f('ix_usuario_locales_user_id'), 'usuario_locales', ['user_id'], unique=False)
    
    # Now modify existing tables - add columns as nullable first
    op.add_column('products', sa.Column('tienda_id', sa.Uuid(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Update existing products to use the default tienda
    op.execute(f"UPDATE products SET tienda_id = '{tienda_id}' WHERE tienda_id IS NULL")
    
    # Migrate existing stock to stock_por_local
    op.execute(f"""
        INSERT INTO stock_por_local (id, producto_id, local_id, cantidad, stock_minimo, costo_promedio, valor_total_inventario, updated_at)
        SELECT 
            gen_random_uuid(),
            id as producto_id,
            '{local_id}' as local_id,
            COALESCE(stock, 0) as cantidad,
            0 as stock_minimo,
            COALESCE(precio_base, 0) as costo_promedio,
            COALESCE(stock, 0) * COALESCE(precio_base, 0) as valor_total_inventario,
            NOW() as updated_at
        FROM products
        WHERE stock IS NOT NULL
    """)
    
    # Update existing users to use the default tienda
    op.add_column('users', sa.Column('tienda_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('local_principal_id', sa.Uuid(), nullable=True))
    
    op.execute(f"UPDATE users SET tienda_id = '{tienda_id}', local_principal_id = '{local_id}' WHERE tienda_id IS NULL")
    
    # Now make the columns NOT NULL and add constraints
    op.alter_column('products', 'tienda_id', nullable=False)
    op.create_index(op.f('ix_products_tienda_id'), 'products', ['tienda_id'], unique=False)
    op.create_foreign_key(None, 'products', 'tiendas', ['tienda_id'], ['id'])
    
    op.create_index(op.f('ix_users_tienda_id'), 'users', ['tienda_id'], unique=False)
    op.create_foreign_key(None, 'users', 'locales', ['local_principal_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tiendas', ['tienda_id'], ['id'])
    
    # Finally, drop the old stock column
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tienda_id'), table_name='users')
    op.drop_column('users', 'local_principal_id')
    op.drop_column('users', 'tienda_id')
    op.add_column('products', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_tienda_id'), table_name='products')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'tienda_id')
    op.drop_index(op.f('ix_usuario_locales_user_id'), table_name='usuario_locales')
    op.drop_index(op.f('ix_usuario_locales_local_id'), table_name='usuario_locales')
    op.drop_table('usuario_locales')
    op.drop_index(op.f('ix_transferencias_inventario_producto_id'), table_name='transferencias_inventario')
    op.drop_index(op.f('ix_transferencias_inventario_local_origen_id'), table_name='transferencias_inventario')
    op.drop_index(op.f('ix_transferencias_inventario_local_destino_id'), table_name='transferencias_inventario')
    op.drop_table('transferencias_inventario')
    op.drop_index(op.f('ix_stock_por_local_producto_id'), table_name='stock_por_local')
    op.drop_index(op.f('ix_stock_por_local_local_id'), table_name='stock_por_local')
    op.drop_table('stock_por_local')
    op.drop_index(op.f('ix_locales_tienda_id'), table_name='locales')
    op.drop_index(op.f('ix_locales_codigo'), table_name='locales')
    op.drop_table('locales')
    op.drop_index(op.f('ix_tiendas_codigo'), table_name='tiendas')
    op.drop_table('tiendas')
    # ### end Alembic commands ###