"""add movimientos_inventario table

Revision ID: c03bcd18c789
Revises: 593794078f1c
Create Date: 2025-07-27 16:45:01.425760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c03bcd18c789'
down_revision: Union[str, Sequence[str], None] = '593794078f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=10), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('stock_anterior', sa.Integer(), nullable=False),
    sa.Column('stock_posterior', sa.Integer(), nullable=False),
    sa.Column('referencia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos_inventario')
    # ### end Alembic commands ###
